sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: M48pmIFwUQlewnwwH9oaRNmE+PO+9m7Koi5qqgG8l1udsaOAIuHNBgFwVLs1MEfSIds7W+zz/c7O/+XoAUi0vr0hg1DR+pHRl5On+gL03eReYwpHASPzBRzCkRc2AsT1MTKOrVWIQSpc/9w2VlHywKqUKVKhqO7G8VHSizI/tOgraXOWmlA6E4hbcbjmD/uzPZYcPuPQFLFl2eAu0EauLBbW5wGCpkeEzpAyli36UF8Ua6e1xSHtaba54iP5GdyTjYHnwkSaCT49xAQ3NGFSqB1TO3z7VxX5lfdxWRcHQldpFwEL/vseiU1yWDHUBJErmkFpNYtrR0Fh+5sO03RncoQDfRDPqmB3UmvI8hwn3FQ5wHYQWS08SN1ZM5SjJMgYVDaW9tX7IHwWZ4vBJlyBivNgL5O/piHwLHQ3U+z2xeLKF4WFoOyrydCfWrGA8w32JDgw4XcAcXmCgE6xKHrQiTVrZxcv4jj7Z4cz+HONpP4nRLl/dt/2kwK76Kii4NlQiZ8CR895lNLTAHPpSkSlQ9i9eBtzLgBo6Gh1Ktnht+vOXxpktBhGs8QBSG/y6z4rBRaSfTHs+6ig1zluSr/crdP6d6N623NhSVXrhD+npQMJowy51n1VysJVTtg/YFa+JW9kR+SCRsvLUFVMOeb7a/98rHgtg1UpjKrNn96h1Zs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Recollections-of-the-Private-Life-of-Napoleon-Volume-11_3578
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy